for i = 1 : length(results)
    figure, subplot(211), imagesc(results{i}.match_score), title('match score'),...
    subplot(212), imagesc(results{i}.n_match_score), title('normalized'),...
    suptitle(sprintf('%d -> %d',i, i + 1));
end